version: '3'

services:
    web:
        container_name: ml_api
        build: 
            dockerfile: Dockerfile
            context: ./
        ports: 
            - "5000:5000"
        tty: True
        
